name: "Tests"
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
jobs:
  zig_nix_pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
    # - run: ./dev/test.sh test_manual_build_prebuilt
    - uses: mxschmitt/action-tmate@v3

